import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
<<<<<<< HEAD
import { SpeedInsights } from "@vercel/speed-insights/react"; // Added this import
import React from "react";
=======
import { SpeedInsights } from "@vercel/speed-insights/react";
>>>>>>> 47657bdc90702c3d231521b9de7fb7ba50f1b673

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Build your business with Next Logic AI and Design",
  description: "Generated by Next Logic",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics /> {/* Added to use the imported Analytics */}
        <SpeedInsights /> {/* Added to use SpeedInsights if intended */}
      </body>
    </html>
  );
}